import React from 'react'
import type { JSX } from 'react/jsx-runtime'



// Component
function EstimatorTemplateTextarea() {
    return <textarea id={"tiny-react_65003222311772978487726"} style={{display:"none"}}>
    	{`<p>Hey,</p><p></p><p><code class="ai-prompt"> You are writing a very short proposal introduction for a construction estimator.<br>Rules:<br>Write exactly 2 sentences.<br>The first sentence must start with:<br>“Starting with a recent project of scope_of_project , link_of_project…”<br>Mention responsibilities such as:<br>quantity takeoff<br>BOQ preparation<br>material and labor estimation<br>reviewing drawings<br>Mention one common issue solved, such as:<br>missing quantities<br>drawing inconsistencies<br>unclear scope<br>Keep sentences short and easy to scan.<br>Do not add software names.<br>Do not add extra explanation.<br>Do not exceed 2 sentences.</code></p><p></p><p>Here's a quick video of my work:</p><p>https://drive.google.com/file/d/12PpJngg9k94mTq00CMGnKOVWtu_KEhwt/view?usp=sharing</p><p></p><p><code class="ai-prompt"> Rewrite the process steps for the job.<br>Rules:<br>Write 4–5 bullet points only.<br>Each step must describe a clear part of the workflow.<br>Do not use the word “I”.<br>Do not mention specific software.<br>Do not exaggerate or add claims not mentioned.<br>Steps must feel natural for an experienced estimator.<br>Keep each step one short sentence.<br>Example structure:<br>• Review drawings and specifications to define the full scope of work.<br>• Prepare a sample estimate to confirm expectations before full execution.<br>• Perform detailed quantity takeoffs and verify scope coverage.<br>• Coordinate revisions until quantities and scope align with project needs.<br>• Deliver organized Excel estimates and marked drawings.</code></p><p></p><p>My projects:</p><p><code class="ai-prompt"> Select 3–5 projects from the provided list that best match the job.<br>Rules:<br>Use exact project names provided.<br>Do not invent projects.<br>Format exactly like this:<br>(Project Name / Scope)<br>Link<br>Example:<br>Pelham High School / Concrete & Masonry<br>https://drive.google.com/drive/folders/1BF2bw4mIQ04wYIQj0VJ-at1BpXCAdc8q?usp=sharing</code></p><p></p><p>I am Sardar Noman, A cost estimator who delivered accurate, construction-ready takeoffs and bid-winning estimates for 20+ US projects, ensuring clear, submission-ready Excel files and designs.</p><p></p><p>GYMNASIUM ($1.4M accurate):</p><p>PlanSwift : https://drive.google.com/file/d/1Yz7TUNG2h0Mtc4GuONSq47Aw2WsTDHI9/view?usp=sharing</p><p>Excel: https://docs.google.com/spreadsheets/d/15T-_tXIablkr4Qx2DtJojSqlbPiXh6hx/edit?usp=sharing</p><p></p><p>Sharing the link of sample estimates that work best for your use case:</p><p>https://docs.google.com/spreadsheets/d/1xO2VhzAubEsPVvHaJCPIdXkE3mZB8umm/edit?usp=sharing</p><p></p><p>Let's get on call to discuss further and make it work.</p><p>Regards,</p><p>Noman</p>`}
    </textarea>}


export default EstimatorTemplateTextarea
